name: Store Tracker Automation

on:
  schedule:
    - cron: '0 21 * * *'  # Daily 2:00 AM Pakistan time (21:00 UTC)
  workflow_dispatch:  # Manual run ka option bhi rahega

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run Store Tracker Script
        run: |
          python store_tracker.py
